server:
  port: 38034
  servlet:
    context-path: /chat-api

spring:
  application:
    name: rubber-at-tennis-chat
  profiles:
    active: dev
  jackson:
    date-format:  "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+08:00"
    default-property-inclusion: non_empty
